// import tinola from "../const/tinola";

import * as Recipe from "../const";

const foods = [
  {
    id: "1",
    name: "Goto",
    description:
      "Goto has been famous in the Philippines because it is affordable and can easily satisfy hunger.",
    fullDescription:
      "Goto is a type of rice porridge with innards of either pig or cow. This Special Goto Recipe uses both ox tripe and pig intestine. Goto has been famous in the Philippines because it is affordable and can easily satisfy hunger. This has also been a breakfast favorite and a rainy day comfort food.",
    ingredients: [
      " 1 cup rice",
      " 200 grams boiled and tender ox tripe ( tuwalya ng baka)",
      " 1/4 cup ginger strips",
      " 3 stalks spring onions",
      " salt and pepper to taste",
      " fish sauce( patis=optional)",
      " 1 litre of water or more",
      " 1/4 cup toasted garlic",
    ],
    recipe: Recipe.tinola,
    image: require("../assets/recipes/goto.jpg"),
  },
  {
    id: "2",
    name: "Ginataang Alimasag",
    description: "Alimasag na may gata",
    ingredients: "Cheese Pizza",
    image: require("../assets/recipes/ginataang-alimasag.jpg"),
  },
  {
    id: "3",
    name: "Tinolang Manok",
    description: "Ito ay isang uri ng chicken soup sa bansang Pilipinas",
    ingredients: "Fried Chicken",
    recipe: Recipe.tinola,
    image: require("../assets/recipes/tinola-manok.jpg"),
  },
  {
    id: "4",
    name: "Sinangag",
    description: "Fried rice sa English",
    ingredients: "Salmon Meat",
    image: require("../assets/recipes/sinangag.jpg"),
  },
  {
    id: "5",
    name: "Adobong Isda",
    description: "Ito ay Tilapiang isda na inadobo",
    ingredients: "Tilapia",
    price: "8.30",
    image: require("../assets/recipes/adobong-isda.jpg"),
  },
  {
    id: "6",
    name: "Adobong Sitaw",
    description: "Gulay na sitaw na inadobo",
    ingredients: "Sitaw",
    price: "7.10",
    image: require("../assets/recipes/adobong-sitaw.jpg"),
  },
  {
    id: "7",
    name: "Ginisang Ampalaya",
    description: "Ito ay ginisang ampalaya na may halong itlog",
    ingredients: "Ampalaya",
    price: "5.10",
    image: require("../assets/recipes/ampalaya.jpg"),
  },
  {
    id: "8",
    name: "Banana Que",
    description: "Ito ay saging na prinito na may asukal",
    ingredients: "Saging",
    price: "9.55",
    image: require("../assets/recipes/banana-que.jpg"),
  },
  {
    id: "9",
    name: "Bibingka",
    description: "a Philippine cake that is made with rice flour, water, and sometimes other ingredients ",
    ingredients: "rice flour",
    price: "9.55",
    image: require("../assets/recipes/bibingka.jpg"),
  },
  {
    id: "10",
    name: "Buko Pie",
    description: "a Filipino-style coconut pie made of fresh, tender young coconut meat combined with a creamy filling and enclosed in a flaky pie",
    ingredients: "Buko",
    price: "8.30",
    image: require("../assets/recipes/buko-pie.jpg"),
  },
  {
    id: "11",
    name: "Chicken Curry",
    description: "Filipino Style Chicken Curry cooked with potatoes, carrots and capsicum in coconut milk with mild curry powder",
    ingredients: "Chicken",
    price: "7.10",
    image: require("../assets/recipes/chicken-curry.jpg"),
  },
  {
    id: "12",
    name: "Longsilog",
    description: "Gawa sa pinaghalong Longganisa at itlog",
    ingredients: "Itlog",
    price: "5.10",
    image: require("../assets/recipes/longsilog.jpg"),
  },
  {
    id: "13",
    name: "Pinakbet",
    description: "Pinakbet is made from mixed vegetables sautéed in fish or shrimp sauce",
    ingredients: "fish",
    price: "9.55",
    image: require("../assets/recipes/pinakbet.jpg"),
  },
  {
    id: "14",
    name: "Buko Salad",
    description: " Sweet young coconut salad is a dessert dish that makes use of shredded young coconut as the main ingredient",
    ingredients: "Buko",
    price: "9.55",
    image: require("../assets/recipes/salad.jpg"),
  },
  {
    id: "15",
    name: "Spaghetti",
    description: "a Filipino-style spaghetti",
    ingredients: "spaghetti",
    price: "8.30",
    image: require("../assets/recipes/spag.jpg"),
  },
  {
    id: "16",
    name: "Tinolang Tahong",
    description: "Type of soup with mussels",
    ingredients: "Tahong",
    price: "7.10",
    image: require("../assets/recipes/tinolang-tahong.jpg"),
  },
  {
    id: "17",
    name: "Turon",
    description: "a Philippine snack made of thinly sliced bananas (preferably saba or Cardaba bananas), dusted with brown sugar, rolled in a spring roll wrapper and fried till the wrapper is crisp",
    ingredients: "saging",
    price: "5.10",
    image: require("../assets/recipes/turon.jpg"),
  },
  {
    id: "18",
    name: "Ukoy",
    description: "Filipino crispy deep-fried fritters made with glutinous rice batter, unshelled small shrimp, and various vegetables",
    ingredients: "Shrimp",
    price: "9.55",
    image: require("../assets/recipes/ukoy.jpg"),
  },

];

export default foods;
